# -*- coding: utf-8 -*-
"""OBĚŠENEC 4.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRtq16FJPfSy6X2EE-nyyyUsgiVTNLp9

**PRO ZPUŠTĚNÍ STISKNI Ctrl + F9**
"""



def sibenice(zivoty):
  if zivoty == 20:
    print(' ')

  if zivoty == 19:
    print('_____________')

  elif zivoty == 18:
    print('      ')
    print('      ')
    print('      ')
    print('      |')
    print('______|______ ')
 

  elif zivoty == 17:
    print('      |')
    print('      |')
    print('      |')
    print('      |')
    print('______|______ ')
 
  

  elif zivoty == 16:
    print('       _____')
    print('      |')
    print('      |')
    print('      |')
    print('      |')
    print('______|______ ')
 

  elif zivoty == 15:
    print('       __________')
    print('      |')
    print('      |')
    print('      |')
    print('      |')
    print('______|______ ')
 
  
    
  elif zivoty == 14:
    print('       __________')
    print('      |  ')
    print('      |/ ')
    print('      |')
    print('      |')
    print('______|______ ')
 
 
    
  elif zivoty == 13:
    print('       __________')
    print('      | / ')
    print('      |/ ')
    print('      |')
    print('      |')
    print('______|______ ')
 
   
    
  elif zivoty == 12:
    print('       __________')
    print('      | /       |')
    print('      |/         ')
    print('      |          ')
    print('      |          ')
    print('______|______    ')  
 

    
  elif zivoty == 11:
    print('       __________')
    print('      | /       |')
    print('      |/         ')
    print('      |          ')
    print('      |          ')
    print('______|______    ')  
 

    
  elif zivoty == 10:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |          ')
    print('      |          ')
    print('______|______    ') 

    
  elif zivoty == 9:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |          ')
    print('      |          ')
    print('______|______    ') 
 

    
  elif zivoty == 8:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |         | ')
    print('      |          ')
    print('______|______    ') 
 

    
  elif zivoty == 7:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |         | ')
    print('      |          ')
    print('______|______    ') 
 

    
  elif zivoty == 6:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |         |\ ')
    print('      |          ')
    print('______|______    ') 
 

    
  elif zivoty == 5:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |        /|\ ')
    print('      |          ')
    print('______|______    ') 
 

    
  elif zivoty == 4:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |        /|\ ')
    print('      |          \ ')
    print('______|______    ') 
 

    
  elif zivoty == 3:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |        /|\ ')
    print('      |          \ ')
    print('______|______    ') 
 

    
  elif zivoty == 2:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |        /|\ ')
    print('      |        / \ ')
    print('______|______       ') 
 

    
  elif zivoty == 1:
    print('       __________')
    print('      | /       |')
    print('      |/        O')
    print('      |        /|\ ')
    print('      |        / \ ')
    print('______|______       ') 
 

    
  elif zivoty == 0:
    print('       __________')
    print('      | /       |')
    print('      |/        0')
    print('      |        /|\ ')
    print('      |        / \ ')
    print('______|______       ') 
 

    

  else:
    print(' ')

import time
import getpass
import random
             

def hangman(): 
  pole_pismena = ['_'] * 5                  #pole na pismena

  oddelovac = 50 * '_'



  print('Ahoj, tento kód má 170 řádků doufám že se ti bude líbit!')
  print('Tato hra se jmenuje oběšenec. Jestli ji neznáš, tak je to o tom, že hádáš po písmenech slovo. Máš 20 životů a když je ztratíš, tak jsi prohrál.')
  print('V žádném hádaném slově se neopakují písmena. Hraje se na háčky a čárky.')

  print(oddelovac)
  print('Tato hra má 2 módy (NORMAL a S KAMARÁDEM). Normal je normální a s kamarádem znamená, že ti slovo zadá kamarád.')
  mod = input('Zadej jeden z módů. pro NORMAL 1 a pro S KAMARÁDEM 2: ')
  print(oddelovac)


                # PRVNÍ MÓD

  if mod == '1':
    
    print('HODNĚ ŠTĚSTÍ!')
    print('Jsou tu i funkce NÁPOVĚDA a QUIT. Když napíšes nápověda tak se ti zobrazí 3. písmeno. Ale pozor! Ubere ti to 7 životů. A když napíšeš q tak ukončíš hru.')

                                                                                                    # zbrojnoš 
    slova = 'oskar', 'strom', 'brána', 'tesco', 'batoh', 'démon', 'rusko', 'tukan', 'zumba', 'cepín', 'rynéř', 'hrnek', 'mobil', 'sport', 'morek', 'srdce', 'sirup', 'Srnka', 'Sonda', 'Cesta', 'Culík', 'Batoh', 'Beran', 'honec'
    slovo = random.choice(slova)
    
    zivoty = 20
    body = 0    
    hadana_pismena = ''

    while body != 5:      # aby hra az najde 5 pismen

      print(oddelovac)
      
      print('písmena co jsi hádal:', hadana_pismena)
      print(oddelovac)
      print(pole_pismena)
      print(oddelovac)

      pismeno = input('Zadej písmeno: ')
      hadana_pismena = hadana_pismena + pismeno + ', '

      
      if pismeno == slovo[0] or pismeno == slovo[1] or pismeno == slovo[2] or pismeno == slovo[3] or pismeno == slovo[4]:
        print('Správně!')
        body = body + 1
        pozice = slovo.find(pismeno)       # najde pozici
        pismeno_up = pismeno.upper()         # caps lock
        pole_pismena[pozice] = pismeno_up      # pokud je spravne dá pismeno do pole na písmena


      
      elif pismeno == 'oskar545':
        print(slovo)

      elif pismeno == 'nápověda':
        pole_pismena[2] = slovo[2]
        print(pole_pismena)
        zivoty = zivoty - 7

      elif pismeno == 'q':
        break
        
      elif zivoty <= 0:
        break

      else:
        print('Špatně!')
        zivoty = zivoty - 1
        print('máš', zivoty, 'životů')
        sibenice(zivoty)
    
    
    if zivoty <= 0:
      print(oddelovac)
      print('slovo bylo', slovo)

    elif pismeno == 'q':
      print(oddelovac)
      print('slovo bylo', slovo)
      print('zbylo ti', zivoty, 'životů')

    
        

      
    else:
      print(oddelovac)
      print('VYHRÁL JSI! PŘÍŠTĚ ŠIBENICI NEUNIKNEŠ!')
      print('zbylo ti', zivoty, 'životů')



        # DRUHÝ MÓD



  elif mod == '2':
    
    pole_pismena = ['_'] * 5
    hadana_pismena = ' '
    body = 0
    zivoty = 20

    print('Je tu i funkce QUIT. Pro ukončení hry zadejte do pole na písmena q.')
    print('V tomto módu ti slovo zadá kamarád.')
    print('Slovo může mít háčky a čárky ale žádné písmeno se nesmí opakovat. Zadávej jen v malých písmenech (ať to kamaráda nepoplete).')
    print('HODNĚ ŠTĚSTÍ')
    print('Zavři oči a nech kamaráda zadat slovo.')
    print(oddelovac)
    time.sleep(7)
    
    print('Pokud tě nenapadá slovo tak tu mám pro tebe pár tipů: srdce sirup Srnka Sonda Cesta Culík Batoh Beran. a ještě pár zákeřnejších slovíček: jětie - zajetí, rynéř - zbrojnoš, honec - jezdec předvoje. ')
    slovo = getpass.getpass('Zadej slovo: ')
    

    
    while body != 5:
      
      print(oddelovac)
      
      print('písmena co jsi hádal:', hadana_pismena)
      print(oddelovac)

      print(pole_pismena)
      print(oddelovac)

      pismeno = input('Zadej písmeno: ')
      hadana_pismena = hadana_pismena + pismeno + ', '

      
      if pismeno == slovo[0] or pismeno == slovo[1] or pismeno == slovo[2] or pismeno == slovo[3] or pismeno == slovo[4]:
        print('Správně!')
        body = body + 1
        pozice = slovo.find(pismeno)       # najde pozici
        pismeno_up = pismeno.upper()         # caps lock
        pole_pismena[pozice] = pismeno_up      # pokud je spravne dá pismeno do pole na písmena
        print(pole_pismena)

      elif pismeno == 'q':
        break
        
      elif zivoty <= 0:
        break


      else:
        print('Špatně!')
        zivoty = zivoty - 1
        print('máš', zivoty, 'životů')
        sibenice(zivoty)
    
    
    if zivoty <= 0:
      print(oddelovac)
      print('slovo bylo', slovo)

    elif pismeno == 'q':
      print(oddelovac)
      print('slovo bylo', slovo)
      print('zbylo ti', zivoty, 'životů')

    else:
      print(oddelovac)
      print('VYHRÁL JSI! PŘÍŠTĚ ŠIBENICI NEUNIKNEŠ!')
      print('zbylo ti', zivoty, 'životů')
    


  else:
    print('tento mód neznám!')